apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      run: backend
  replicas: 1
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
      - name: backend
        imagePullPolicy: Always
        image: 040154159363.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
            - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: mern-backend-svc
  labels:
    run: backend
    app: mern-app
spec:
  selector:
    name: backend 
  type: LoadBalancer
  ports:
   - name: backend
     port: 5000
     targetPort: 5000
     protocol: TCP

