apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
        app: mern-app
    spec:
      containers: 
        - image: 040154159363.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          imagePullPolicy: Always
          name: frontend
          ports: 
            - containerPort: 3000
      imagePullSecrets:
            - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: mern-frontend-svc
  labels:
    name: frontend
    app: mern-app
spec:
  selector:
    name: frontend 
  type: LoadBalancer
  ports:
   - name: frontend
     port: 3000
     targetPort: 3000
     protocol: TCP
